apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: kuberse
  description: Kuberse -- self-bootstrapping Kubernetes platform
  annotations:
    backstage.io/techdocs-ref: dir:.
  links:
    - url: ${GIT_BASE_URL}/kuberse
      title: Registry Repo
spec:
  owner: group:default/admins

---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: kuberse-platform
  description: Kuberse platform -- all systems, plugins, and infrastructure components
spec:
  targets:
    - ./platform/**/catalog-info.yaml
    - ./runners/**/catalog-info.yaml
    - ./plugins/**/catalog-info.yaml

---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: kuberse-org
  description: Kuberse organisation -- users and groups
spec:
  type: file
  targets:
    - ./org.yaml
