apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: runners
    repoURL: oci://gitea-http.platform.svc.cluster.local:3000/marioapgs/kuberse/helm/runners
    targetRevision: latest
    helm:
      values: |
        arc-controller:
          enabled: true
          gha-runner-scale-set-controller:
            metrics:
              controllerManagerAddr: ":8080"
              listenerAddr: ":8080"
              listenerEndpoint: "/metrics"
            resources:
              limits:
                cpu: 200m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: runners
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
