apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubrain
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: platform
    repoURL: oci://gitea-http.platform.svc.cluster.local:3000/marioapgs/kuberse/helm/platform
    targetRevision: latest
    helm:
      values: |
        kubrain:
          enabled: true
          replicaCount: 1
          ingress:
            enabled: true
            className: nginx
            host: "kubrain.kuberse.net"
            tls:
              enabled: false
          image:
            repository: gitea-http.platform.svc.cluster.local:3000/marioapgs/kuberse/img/kubrain
            tag: latest
            pullPolicy: Always
          vault:
            enabled: true
            host: http://vault.platform.svc.cluster.local:8200
            serviceAccountName: kubrain
            secretPath: kubrain/config
            role:
              ttl: '24h'
              paths:
                - path: 'secret/data/kubrain/*'
                  capabilities: ['create', 'read', 'update']
                - path: 'secret/metadata/kubrain/*'
                  capabilities: ['read', 'list']
                - path: 'secret/data/*'
                  capabilities: ['create', 'read', 'update']
                - path: 'secret/metadata/*'
                  capabilities: ['read', 'list']
                - path: 'buildapps/data/*'
                  capabilities: ['create', 'read', 'update', 'delete', 'list']
                - path: 'buildapps/metadata/*'
                  capabilities: ['read', 'list', 'delete']
                - path: 'sys/policies/acl/*'
                  capabilities: ['create', 'read', 'update', 'delete']
                - path: 'auth/kubernetes/role/*'
                  capabilities: ['create', 'read', 'update', 'delete']
          configFile:
            enabled: true
            content: |
              database:
                url: env.PG_CONNECTION_STRING
                synchronize: true
              ingestion:
                github:
                  owner: marioapgs
                  match: "**/kuberse-entity.yaml"
                  fetch: "*/5 * * * *"
                  token: k8s.platform.kuberse-config.github_token
                gitea:
                  url: http://gitea-http.platform.svc.cluster.local:3000
                  organization: marioapgs
                  match: "**/kuberse-entity.yaml"
                  fetch: "*/5 * * * *"
                  token: k8s.platform.kuberse-config.gitea_token
              argocd:
                url: https://argocd-server.argocd.svc.cluster.local
                insecure: true
                username: admin
                password: k8s.platform.kuberse-config.admin_password
              vault:
                url: env.VAULT_URL
              buildapp:
                chartRepo: oci://gitea-http.platform.svc.cluster.local:3000/marioapgs/kuberse/helm/buildapp
                chartVersion: latest
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
