apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: platform
    repoURL: oci://${REGISTRY_URL}/${ORG_NAME}/kuberse/helm/platform
    targetRevision: latest
    helm:
      values: |
        vault:
          enabled: true
          vaultConfig:
            namespace: platform
            serviceName: vault
            address: "http://vault.platform.svc.cluster.local:8200"
            initSecretName: vault-init-keys
          ingress:
            enabled: true
            className: nginx
            host: "vault.${BASE_DOMAIN}"
            tls:
              enabled: false
          moduleConfig:
            enabled: true
            schedule: "*/5 * * * *"
          vault:
            server:
              resources:
                requests:
                  memory: 256Mi
                  cpu: 250m
                limits:
                  memory: 512Mi
                  cpu: 500m
              ha:
                enabled: true
                replicas: 1
              dataStorage:
                enabled: true
                size: 10Gi
                storageClass: null
            injector:
              enabled: true
          vault-secrets-operator:
            enabled: true
            defaultVaultConnection:
              enabled: false
            csi:
              enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  ignoreDifferences:
    - group: batch
      kind: Job
      jsonPointers:
        - /status
