apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: platform
    repoURL: oci://gitea-http.platform.svc.cluster.local:3000/marioapgs/kuberse/helm/platform
    targetRevision: latest
    helm:
      values: |
        argocd-config:
          enabled: true
          ingress:
            host: "argocd.kuberse.net"
          oidc:
            url: "https://argocd.kuberse.net"
            issuer: "https://auth.kuberse.net/application/o/argocd/"
          authentikOidc:
            redirectUris:
              - url: "https://argocd.kuberse.net/auth/callback"
                matchingMode: strict
            application:
              launchUrl: "https://argocd.kuberse.net"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
