apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: platform
    repoURL: oci://${REGISTRY_URL}/${ORG_NAME}/kuberse/helm/platform
    targetRevision: latest
    helm:
      values: |
        ingress-nginx:
          enabled: true
          ingress-nginx:
            controller:
              service:
                type: NodePort
                nodePorts:
                  http: 30080
                  https: 30443
              hostPort:
                enabled: false
              hostNetwork: false
              resources:
                requests:
                  cpu: 100m
                  memory: 90Mi
                limits:
                  cpu: 200m
                  memory: 256Mi
              ingressClassResource:
                default: true
              config:
                ssl-redirect: "false"
                force-ssl-redirect: "false"
                use-forwarded-headers: "true"
                compute-full-forwarded-for: "true"
              metrics:
                enabled: true
                serviceMonitor:
                  enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
