apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: platform
    repoURL: oci://gitea-http.platform.svc.cluster.local:3000/marioapgs/kuberse/helm/platform
    targetRevision: latest
    helm:
      values: |
        postgres:
          enabled: true
          persistence:
            enabled: true
            size: "10Gi"
            storageClass: ""
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          dbProvisioner:
            cronSchedule: "*/5 * * * *"
            namespaceToSearch: null
          vault:
            enabled: true
            host: http://vault.platform.svc.cluster.local:8200
            serviceAccountName: postgres-sa
            secretPath: postgres/config
            role:
              ttl: "24h"
              paths:
                - path: "secret/data/postgres/*"
                  capabilities: ["read"]
                - path: "secret/metadata/postgres/*"
                  capabilities: ["read", "list"]
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
